services:
  app:
    build: .
    container_name: fastapi-crud-products
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGODB_PRODUCTION_URL}
    volumes:
      - .:/app
      - ./db:/db # Volume para o SQLite
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: fastapi-crud-products-mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb-data:/data/db # Volume para o MongoDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: # Volume separado para o MongoDB
